import { Club, Country } from './types';

export const COUNTRIES: Country[] = [
  {
    id: 'egypt',
    name: 'Egypt',
    code: 'EG',
    clubs: ['al-ahly', 'zamalek', 'pyramids'],
    performanceSummary: 'Most successful nation in CAF history with 16 Champions League titles.',
  },
  {
    id: 'tunisia',
    name: 'Tunisia',
    code: 'TN',
    clubs: ['esperance', 'club-africain', 'cs-sfaxien'],
    performanceSummary: 'Consistent continental presence with 6 Champions League titles.',
  },
  {
    id: 'morocco',
    name: 'Morocco',
    code: 'MA',
    clubs: ['wydad', 'raja', 'as-far'],
    performanceSummary: 'Current powerhouse in both Champions League and Confederation Cup.',
  },
  {
    id: 'south-africa',
    name: 'South Africa',
    code: 'ZA',
    clubs: ['sundowns', 'kaizer-chiefs', 'orlando-pirates'],
    performanceSummary: 'Technically advanced league with growing continental influence.',
  },
  {
    id: 'dr-congo',
    name: 'DR Congo',
    code: 'CD',
    clubs: ['tp-mazembe', 'as-vita'],
    performanceSummary: 'Home to TP Mazembe, one of the most feared teams on the continent.',
  },
  {
    id: 'algeria',
    name: 'Algeria',
    code: 'DZ',
    clubs: ['cr-belouizdad', 'usm-alger'],
    performanceSummary: 'Recent CL deep runs and strong domestic competition.',
  },
  {
    id: 'senegal',
    name: 'Senegal',
    code: 'SN',
    clubs: ['generation-foot', 'jaraaf'],
    performanceSummary: 'Strong youth pipeline and emerging continental presence.',
  },
  {
    id: 'cameroon',
    name: 'Cameroon',
    code: 'CM',
    clubs: ['coton-sport', 'canon-yaounde'],
    performanceSummary: 'Historical CAF presence with legendary clubs.',
  },
  {
    id: 'kenya',
    name: 'Kenya',
    code: 'KE',
    clubs: ['gor-mahia', 'afc-leopards'],
    performanceSummary: "East Africa's strongest footballing nation.",
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    code: 'NG',
    clubs: ['enyimba', 'rivers-united'],
    performanceSummary: 'Super Eagles pipeline and historical continental success.',
  },
];

export const CLUBS: Record<string, Club> = {
  'al-ahly': {
    id: 'al-ahly',
    name: 'Al Ahly SC',
    country: 'Egypt',
    rank: 1,
    tier: 'A',
    titles: 11,
    leaguePosition: 1,
    lastFive: ['W', 'W', 'D', 'W', 'W'],
    nextFixture: 'vs Zamalek (CAF CL)',
    formation: '4-3-3',
    stadium: 'Cairo International Stadium',
    capacity: '75,000',
    manager: {
      name: 'Marcel Koller',
      winPercentage: 72.5,
      preferredFormations: ['4-3-3', '4-2-3-1'],
      careerTimeline: [
        { year: '2022-Present', club: 'Al Ahly' },
        { year: '2017-2020', club: 'FC Basel' },
        { year: '2011-2017', club: 'Austria National Team' },
      ],
      tacticalAnalysis: 'Koller emphasizes a high-intensity pressing game combined with structured positional play. His Al Ahly side excels in quick transitions and maintaining a compact defensive shape.',
      quote: "We play to dominate, but we must remain disciplined in our structure to win consistently in Africa."
    },
    squad: [
      { id: 'p1', name: 'Mohamed El Shenawy', position: 'GK', age: 35, nationality: 'Egypt', marketValue: '€2.5M', form: 8.5, status: 'fit', scoutNote: 'Elite shot-stopper, but prone to errors under high pressure.' },
      { id: 'p2', name: 'Percy Tau', position: 'RW', age: 30, nationality: 'South Africa', marketValue: '€1.5M', form: 7.8, status: 'fit', scoutNote: 'Dynamic playmaker, key to transitions.' },
      { id: 'p3', name: 'Emam Ashour', position: 'CM', age: 26, nationality: 'Egypt', marketValue: '€3.0M', form: 9.2, status: 'fit', scoutNote: 'Creative force, excellent long-range shooting.' },
      { id: 'p101', name: 'Ramy Rabia', position: 'CB', age: 31, nationality: 'Egypt', marketValue: '€0.8M', form: 6.5, status: 'fit', scoutNote: 'Experienced but lacks agility against fast strikers.', isWeakPoint: true },
      { id: 'p102', name: 'Anthony Modeste', position: 'ST', age: 35, nationality: 'France', marketValue: '€0.5M', form: 5.2, status: 'fit', scoutNote: 'Lacks pace and mobility in the final third.', isWeakPoint: true },
      { id: 'p103', name: 'Khaled Abdelfattah', position: 'RB', age: 25, nationality: 'Egypt', marketValue: '€0.6M', form: 5.8, status: 'fit', scoutNote: 'Often caught out of position during transitions.', isWeakPoint: true },
    ],
    tactics: {
      pressing: 85,
      buildUp: 'positional',
      defensiveLine: 'high',
      transitionSpeed: 90,
    },
  },
  'zamalek': {
    id: 'zamalek',
    name: 'Zamalek SC',
    country: 'Egypt',
    rank: 7,
    tier: 'A',
    titles: 5,
    leaguePosition: 2,
    lastFive: ['W', 'L', 'W', 'D', 'W'],
    nextFixture: 'vs Al Ahly',
    formation: '4-2-3-1',
    stadium: 'Cairo International Stadium',
    capacity: '75,000',
    manager: {
      name: 'José Gomes',
      winPercentage: 58.2,
      preferredFormations: ['4-2-3-1', '4-3-3'],
      careerTimeline: [
        { year: '2024-Present', club: 'Zamalek' },
        { year: '2022-2023', club: 'Chaves' },
        { year: '2020-2021', club: 'Al-Taawoun' },
      ],
      tacticalAnalysis: 'Gomes focuses on technical superiority and fluid attacking movements. He encourages his creative players like Zizo to roam and find pockets of space between the lines.',
      quote: "Football is about the quality of the pass and the intelligence of the movement."
    },
    squad: [
      { id: 'z1', name: 'Zizo', position: 'RW', age: 28, nationality: 'Egypt', marketValue: '€4.5M', form: 9.0, status: 'fit', scoutNote: 'Best player in the league, elite crossing and set-pieces.' },
      { id: 'z101', name: 'Seifeddine Jaziri', position: 'ST', age: 31, nationality: 'Tunisia', marketValue: '€1.0M', form: 7.2, status: 'fit', scoutNote: 'Strong hold-up play, reliable finisher.' },
      { id: 'z102', name: 'Samson Akinyoola', position: 'ST', age: 24, nationality: 'Benin', marketValue: '€0.3M', form: 4.5, status: 'fit', scoutNote: 'Lacks clinical finishing and physical presence.', isWeakPoint: true },
      { id: 'z103', name: 'Mostafa El Zenary', position: 'CB', age: 25, nationality: 'Egypt', marketValue: '€0.4M', form: 5.5, status: 'fit', scoutNote: 'Inconsistent in 1v1 defensive situations.', isWeakPoint: true },
    ],
    tactics: { pressing: 75, buildUp: 'positional', defensiveLine: 'medium', transitionSpeed: 85 },
  },
  'esperance': {
    id: 'esperance',
    name: 'Espérance de Tunis',
    country: 'Tunisia',
    rank: 3,
    tier: 'A',
    titles: 4,
    leaguePosition: 1,
    lastFive: ['W', 'D', 'W', 'L', 'W'],
    nextFixture: 'vs Club Africain',
    formation: '4-2-3-1',
    stadium: 'Stade Hammadi Agrebi',
    capacity: '60,000',
    manager: {
      name: 'Miguel Cardoso',
      winPercentage: 64.1,
      preferredFormations: ['4-2-3-1', '4-1-4-1'],
      careerTimeline: [
        { year: '2024-Present', club: 'Espérance de Tunis' },
        { year: '2021-2022', club: 'Rio Ave' },
        { year: '2019', club: 'AEK Athens' },
      ],
      tacticalAnalysis: 'Cardoso has implemented a more direct and efficient style at Espérance. He prioritizes defensive solidity and quick vertical transitions to exploit the pace of his wingers.',
      quote: "Efficiency in both boxes is what defines champions in continental competitions."
    },
    squad: [
      { id: 'p4', name: 'Yan Sasse', position: 'AM', age: 26, nationality: 'Brazil', marketValue: '€1.2M', form: 8.1, status: 'fit', scoutNote: 'Creative spark, great dribbling skills.' },
      { id: 'p5', name: 'Yassine Meriah', position: 'CB', age: 30, nationality: 'Tunisia', marketValue: '€2.0M', form: 7.5, status: 'fit', scoutNote: 'Solid defender, excellent in the air.' },
      { id: 'p104', name: 'Mohamed Ben Ali', position: 'RB', age: 29, nationality: 'Tunisia', marketValue: '€0.5M', form: 6.2, status: 'fit', scoutNote: 'Struggles against pacey wingers.', isWeakPoint: true },
      { id: 'p105', name: 'Houssem Tka', position: 'CM', age: 23, nationality: 'Tunisia', marketValue: '€0.8M', form: 6.8, status: 'fit', scoutNote: 'Good engine, but decision making can be slow.' },
    ],
    tactics: {
      pressing: 70,
      buildUp: 'direct',
      defensiveLine: 'medium',
      transitionSpeed: 75,
    },
  },
  'wydad': {
    id: 'wydad',
    name: 'Wydad AC',
    country: 'Morocco',
    rank: 4,
    tier: 'A',
    titles: 3,
    leaguePosition: 2,
    lastFive: ['W', 'W', 'D', 'W', 'L'],
    nextFixture: 'vs Raja Casablanca',
    formation: '4-3-3',
    stadium: 'Stade Mohammed V',
    capacity: '67,000',
    manager: {
      name: 'Rulani Mokwena',
      winPercentage: 68.9,
      preferredFormations: ['4-3-3', '3-4-3'],
      careerTimeline: [
        { year: '2024-Present', club: 'Wydad AC' },
        { year: '2020-2024', club: 'Mamelodi Sundowns' },
        { year: '2019-2020', club: 'Orlando Pirates' },
      ],
      tacticalAnalysis: 'A student of the game, Mokwena brings a highly sophisticated positional play model to Wydad. He emphasizes ball retention and numerical superiorities in the build-up phase.',
      quote: "We don't just want to win; we want to win with a clear identity that honors the fans."
    },
    squad: [
      { id: 'w1', name: 'Mounir El Kajoui', position: 'GK', age: 34, nationality: 'Morocco', marketValue: '€1.0M', form: 8.0, status: 'fit' },
      { id: 'w101', name: 'Aymane El Hassouni', position: 'AM', age: 29, nationality: 'Morocco', marketValue: '€1.2M', form: 7.4, status: 'fit' },
      { id: 'w102', name: 'Hamza Regragui', position: 'CB', age: 27, nationality: 'Morocco', marketValue: '€0.6M', form: 5.9, status: 'fit' },
      { id: 'w103', name: 'Zakaria Draoui', position: 'CDM', age: 30, nationality: 'Algeria', marketValue: '€0.9M', form: 6.5, status: 'fit' },
    ],
    tactics: { pressing: 80, buildUp: 'positional', defensiveLine: 'high', transitionSpeed: 85 },
  },
  'raja': {
    id: 'raja',
    name: 'Raja Casablanca',
    country: 'Morocco',
    rank: 5,
    tier: 'A',
    titles: 3,
    leaguePosition: 1,
    lastFive: ['W', 'W', 'W', 'W', 'W'],
    nextFixture: 'vs Wydad AC',
    formation: '4-2-3-1',
    stadium: 'Stade Mohammed V',
    capacity: '67,000',
    manager: {
      name: 'Ricardo Sá Pinto',
      winPercentage: 55.4,
      preferredFormations: ['4-2-3-1', '4-4-2'],
      careerTimeline: [
        { year: '2024-Present', club: 'Raja Casablanca' },
        { year: '2023-2024', club: 'APOEL' },
        { year: '2022-2023', club: 'Esteghlal' },
      ],
      tacticalAnalysis: 'Sá Pinto is known for his passionate leadership and aggressive tactical setup. He demands high work rates and expects his team to dominate the physical battles.',
      quote: "Every match is a final. We play with our hearts and our heads."
    },
    squad: [
      { id: 'r1', name: 'Yousri Bouzok', position: 'LW', age: 27, nationality: 'Algeria', marketValue: '€1.8M', form: 9.1, status: 'fit' },
      { id: 'r101', name: 'Anas Zniti', position: 'GK', age: 35, nationality: 'Morocco', marketValue: '€0.5M', form: 7.0, status: 'fit' },
      { id: 'r102', name: 'Mohamed Boulacsout', position: 'RW', age: 25, nationality: 'Morocco', marketValue: '€0.7M', form: 6.3, status: 'fit' },
      { id: 'r103', name: 'Abdellah Khafifi', position: 'CB', age: 31, nationality: 'Morocco', marketValue: '€0.6M', form: 5.8, status: 'fit' },
    ],
    tactics: { pressing: 75, buildUp: 'positional', defensiveLine: 'medium', transitionSpeed: 80 },
  },
  'sundowns': {
    id: 'sundowns',
    name: 'Mamelodi Sundowns',
    country: 'South Africa',
    rank: 2,
    tier: 'A',
    titles: 1,
    leaguePosition: 1,
    lastFive: ['W', 'W', 'W', 'W', 'D'],
    nextFixture: 'vs Orlando Pirates',
    formation: '4-3-3',
    stadium: 'Loftus Versfeld Stadium',
    capacity: '51,000',
    manager: {
      name: 'Manqoba Mngqithi',
      winPercentage: 70.2,
      preferredFormations: ['4-3-3', '4-2-3-1'],
      careerTimeline: [
        { year: '2024-Present', club: 'Mamelodi Sundowns (Head)' },
        { year: '2014-2024', club: 'Mamelodi Sundowns (Asst/Co)' },
        { year: '2013-2014', club: 'Golden Arrows' },
      ],
      tacticalAnalysis: 'Continuing the Sundowns philosophy, Mngqithi focuses on intricate passing patterns and high-intensity counter-pressing. He utilizes inverted fullbacks to dominate the midfield.',
      quote: "Our strength is in our collective understanding of the space and the ball."
    },
    squad: [
      { id: 'p6', name: 'Ronwen Williams', position: 'GK', age: 32, nationality: 'South Africa', marketValue: '€1.2M', form: 9.0, status: 'fit' },
      { id: 'p7', name: 'Teboho Mokoena', position: 'CM', age: 27, nationality: 'South Africa', marketValue: '€2.2M', form: 8.8, status: 'fit' },
      { id: 'p106', name: 'Mothobi Mvala', position: 'CB', age: 29, nationality: 'South Africa', marketValue: '€0.9M', form: 7.2, status: 'fit' },
      { id: 'p107', name: 'Aubrey Modiba', position: 'LB', age: 28, nationality: 'South Africa', marketValue: '€1.1M', form: 7.5, status: 'fit' },
      { id: 'p108', name: 'Neo Maema', position: 'AM', age: 28, nationality: 'South Africa', marketValue: '€0.8M', form: 6.4, status: 'fit' },
    ],
    tactics: {
      pressing: 90,
      buildUp: 'positional',
      defensiveLine: 'high',
      transitionSpeed: 80,
    },
  },
  'tp-mazembe': {
    id: 'tp-mazembe',
    name: 'TP Mazembe',
    country: 'DR Congo',
    rank: 10,
    tier: 'A',
    titles: 5,
    leaguePosition: 1,
    lastFive: ['W', 'W', 'L', 'W', 'W'],
    nextFixture: 'vs AS Vita Club',
    formation: '4-4-2',
    stadium: 'Stade TP Mazembe',
    capacity: '18,500',
    manager: {
      name: 'Lamine N\'Diaye',
      winPercentage: 66.7,
      preferredFormations: ['4-4-2', '4-3-3'],
      careerTimeline: [
        { year: '2023-Present', club: 'TP Mazembe' },
        { year: '2020-2022', club: 'Horoya AC' },
        { year: '2010-2013', club: 'TP Mazembe' },
      ],
      tacticalAnalysis: 'N\'Diaye has returned to Mazembe to restore their continental dominance. He favors a robust 4-4-2 that relies on powerful wingers and clinical finishing from the front two.',
      quote: "Mazembe is a giant that must always be respected in Africa."
    },
    squad: [
      { id: 'm1', name: 'Philippe Kinzumbi', position: 'RW', age: 25, nationality: 'DR Congo', marketValue: '€0.8M', form: 8.4, status: 'fit' },
      { id: 'm101', name: 'Kevin Mondeko', position: 'CB', age: 28, nationality: 'DR Congo', marketValue: '€0.4M', form: 6.8, status: 'fit' },
      { id: 'm102', name: 'Zemanga Soze', position: 'CM', age: 24, nationality: 'DR Congo', marketValue: '€0.3M', form: 6.1, status: 'fit' },
      { id: 'm103', name: 'Fily Traoré', position: 'ST', age: 22, nationality: 'Mali', marketValue: '€0.5M', form: 7.9, status: 'fit' },
    ],
    tactics: { pressing: 85, buildUp: 'direct', defensiveLine: 'medium', transitionSpeed: 95 },
  },
  'enyimba': {
    id: 'enyimba',
    name: 'Enyimba FC',
    country: 'Nigeria',
    rank: 25,
    tier: 'B',
    titles: 2,
    leaguePosition: 3,
    lastFive: ['D', 'W', 'L', 'W', 'W'],
    nextFixture: 'vs Rivers United',
    formation: '4-3-3',
    stadium: 'Enyimba International Stadium',
    capacity: '16,000',
    manager: {
      name: 'Yemi Olanrewaju',
      winPercentage: 52.8,
      preferredFormations: ['4-3-3', '4-2-3-1'],
      careerTimeline: [
        { year: '2024-Present', club: 'Enyimba FC' },
        { year: '2022-2024', club: 'Enyimba FC (Asst)' },
        { year: '2021-2022', club: 'Vandrezzer FC' },
      ],
      tacticalAnalysis: 'A young, modern coach, Olanrewaju is building a dynamic Enyimba side. He encourages bold attacking play and gives freedom to his young talents to express themselves.',
      quote: "We are building a legacy based on hard work and tactical innovation."
    },
    squad: [
      { id: 'e1', name: 'Chijioke Mbaoma', position: 'ST', age: 22, nationality: 'Nigeria', marketValue: '€0.4M', form: 7.9, status: 'fit' },
      { id: 'e101', name: 'Olorunleke Ojo', position: 'GK', age: 28, nationality: 'Nigeria', marketValue: '€0.2M', form: 7.5, status: 'fit' },
      { id: 'e102', name: 'Pascal Eze', position: 'CB', age: 21, nationality: 'Nigeria', marketValue: '€0.1M', form: 6.2, status: 'fit' },
      { id: 'e103', name: 'Ikenna Cooper', position: 'CM', age: 25, nationality: 'Nigeria', marketValue: '€0.1M', form: 5.8, status: 'fit' },
    ],
    tactics: { pressing: 70, buildUp: 'direct', defensiveLine: 'low', transitionSpeed: 85 },
  },
  'pyramids': {
    id: 'pyramids',
    name: 'Pyramids FC',
    country: 'Egypt',
    rank: 6,
    tier: 'A',
    titles: 0,
    leaguePosition: 3,
    lastFive: ['W', 'D', 'W', 'W', 'L'],
    nextFixture: 'vs Zamalek',
    formation: '4-2-3-1',
    stadium: '30 June Stadium',
    capacity: '30,000',
    manager: {
      name: 'Krunoslav Jurčić',
      winPercentage: 60.5,
      preferredFormations: ['4-2-3-1', '4-3-3'],
      careerTimeline: [{ year: '2024-Present', club: 'Pyramids FC' }],
      tacticalAnalysis: 'Focuses on a balanced approach with strong defensive organization and clinical counter-attacks.',
      quote: "We are here to challenge the traditional hierarchy of Egyptian football."
    },
    squad: [
      { id: 'py1', name: 'Fiston Mayele', position: 'ST', age: 29, nationality: 'DR Congo', marketValue: '€1.8M', form: 8.5, status: 'fit' },
      { id: 'py2', name: 'Mostafa Fathi', position: 'RW', age: 29, nationality: 'Egypt', marketValue: '€1.2M', form: 7.8, status: 'fit' },
    ],
    tactics: { pressing: 75, buildUp: 'positional', defensiveLine: 'medium', transitionSpeed: 80 },
  },
  'club-africain': {
    id: 'club-africain',
    name: 'Club Africain',
    country: 'Tunisia',
    rank: 42,
    tier: 'C',
    titles: 1,
    leaguePosition: 3,
    lastFive: ['D', 'W', 'D', 'W', 'L'],
    nextFixture: 'vs Espérance',
    formation: '4-3-3',
    stadium: 'Stade Olympique de Radès',
    capacity: '60,000',
    manager: {
      name: 'David Bettoni',
      winPercentage: 45.0,
      preferredFormations: ['4-3-3'],
      careerTimeline: [{ year: '2024-Present', club: 'Club Africain' }],
      tacticalAnalysis: 'Emphasizes technical control and high pressing.',
      quote: "The history of this club demands excellence in every performance."
    },
    squad: [
      { id: 'ca1', name: 'Kingsley Eduwo', position: 'ST', age: 27, nationality: 'Nigeria', marketValue: '€0.6M', form: 7.2, status: 'fit' },
    ],
    tactics: { pressing: 80, buildUp: 'positional', defensiveLine: 'high', transitionSpeed: 75 },
  },
  'as-far': {
    id: 'as-far',
    name: 'AS FAR',
    country: 'Morocco',
    rank: 8,
    tier: 'A',
    titles: 1,
    leaguePosition: 2,
    lastFive: ['W', 'W', 'L', 'W', 'W'],
    nextFixture: 'vs Raja Casablanca',
    formation: '4-3-3',
    stadium: 'Prince Moulay Abdellah Stadium',
    capacity: '52,000',
    manager: {
      name: 'Czesław Michniewicz',
      winPercentage: 55.0,
      preferredFormations: ['4-3-3', '4-2-3-1'],
      careerTimeline: [{ year: '2024-Present', club: 'AS FAR' }],
      tacticalAnalysis: 'Pragmatic approach with strong emphasis on set-pieces and defensive transitions.',
      quote: "Discipline is the foundation of our tactical success."
    },
    squad: [
      { id: 'af1', name: 'Rabie Hrimat', position: 'CM', age: 29, nationality: 'Morocco', marketValue: '€1.0M', form: 8.4, status: 'fit' },
    ],
    tactics: { pressing: 70, buildUp: 'direct', defensiveLine: 'medium', transitionSpeed: 90 },
  },
  'orlando-pirates': {
    id: 'orlando-pirates',
    name: 'Orlando Pirates',
    country: 'South Africa',
    rank: 28,
    tier: 'B',
    titles: 1,
    leaguePosition: 2,
    lastFive: ['W', 'W', 'D', 'W', 'W'],
    nextFixture: 'vs Mamelodi Sundowns',
    formation: '4-2-3-1',
    stadium: 'Orlando Stadium',
    capacity: '37,139',
    manager: {
      name: 'Jose Riveiro',
      winPercentage: 62.0,
      preferredFormations: ['4-2-3-1'],
      careerTimeline: [{ year: '2022-Present', club: 'Orlando Pirates' }],
      tacticalAnalysis: 'Fluid attacking football with a focus on wing play and creative freedom.',
      quote: "We play to entertain and to win, in that order of importance."
    },
    squad: [
      { id: 'op1', name: 'Patrick Maswanganyi', position: 'AM', age: 25, nationality: 'South Africa', marketValue: '€0.8M', form: 8.9, status: 'fit' },
    ],
    tactics: { pressing: 75, buildUp: 'positional', defensiveLine: 'medium', transitionSpeed: 85 },
  },
  'cr-belouizdad': {
    id: 'cr-belouizdad',
    name: 'CR Belouizdad',
    country: 'Algeria',
    rank: 9,
    tier: 'A',
    titles: 0,
    leaguePosition: 1,
    lastFive: ['W', 'W', 'D', 'W', 'W'],
    nextFixture: 'vs USM Alger',
    formation: '4-3-3',
    stadium: 'Stade du 5 Juillet',
    capacity: '64,000',
    manager: {
      name: 'Corentin Martins',
      winPercentage: 58.0,
      preferredFormations: ['4-3-3'],
      careerTimeline: [{ year: '2024-Present', club: 'CR Belouizdad' }],
      tacticalAnalysis: 'Possession-based football with a high defensive line.',
      quote: "Control the ball, control the game."
    },
    squad: [
      { id: 'crb1', name: 'Islam Slimani', position: 'ST', age: 35, nationality: 'Algeria', marketValue: '€1.5M', form: 8.2, status: 'fit' },
    ],
    tactics: { pressing: 80, buildUp: 'positional', defensiveLine: 'high', transitionSpeed: 70 },
  },
  'rivers-united': {
    id: 'rivers-united',
    name: 'Rivers United',
    country: 'Nigeria',
    rank: 32,
    tier: 'B',
    titles: 0,
    leaguePosition: 2,
    lastFive: ['W', 'L', 'W', 'D', 'W'],
    nextFixture: 'vs Enyimba FC',
    formation: '4-4-2',
    stadium: 'Adokiye Amiesimaka Stadium',
    capacity: '38,000',
    manager: {
      name: 'Finidi George',
      winPercentage: 54.0,
      preferredFormations: ['4-4-2', '4-3-3'],
      careerTimeline: [{ year: '2024-Present', club: 'Rivers United' }],
      tacticalAnalysis: 'Classic wing play and strong physical presence in the box.',
      quote: "We use our strength and speed to overwhelm the opposition."
    },
    squad: [
      { id: 'ru1', name: 'Nyima Nwagua', position: 'ST', age: 30, nationality: 'Nigeria', marketValue: '€0.2M', form: 7.1, status: 'fit', scoutNote: 'Powerful striker, but lacks pace.' },
      { id: 'ru101', name: 'Kingdom Osayi', position: 'GK', age: 24, nationality: 'Nigeria', marketValue: '€0.1M', form: 5.5, status: 'fit', scoutNote: 'Inconsistent handling of crosses.', isWeakPoint: true },
    ],
    tactics: { pressing: 65, buildUp: 'direct', defensiveLine: 'medium', transitionSpeed: 80 },
  },
  'cs-sfaxien': {
    id: 'cs-sfaxien',
    name: 'CS Sfaxien',
    country: 'Tunisia',
    rank: 35,
    tier: 'B',
    titles: 0,
    leaguePosition: 4,
    lastFive: ['D', 'D', 'W', 'L', 'W'],
    nextFixture: 'vs Espérance',
    formation: '4-4-2',
    stadium: 'Stade Taïeb Mhiri',
    capacity: '11,000',
    manager: { name: 'Alexandre Santos', winPercentage: 50.0, preferredFormations: ['4-4-2'], careerTimeline: [], tacticalAnalysis: 'Solid defensive block.', quote: 'Discipline is key.' },
    squad: [{ id: 'css1', name: 'Alaa Ghram', position: 'CB', age: 22, nationality: 'Tunisia', marketValue: '€0.8M', form: 7.5, status: 'fit' }],
    tactics: { pressing: 60, buildUp: 'direct', defensiveLine: 'low', transitionSpeed: 70 },
  },
  'kaizer-chiefs': {
    id: 'kaizer-chiefs',
    name: 'Kaizer Chiefs',
    country: 'South Africa',
    rank: 30,
    tier: 'B',
    titles: 0,
    leaguePosition: 5,
    lastFive: ['L', 'W', 'D', 'L', 'W'],
    nextFixture: 'vs Orlando Pirates',
    formation: '4-2-3-1',
    stadium: 'FNB Stadium',
    capacity: '94,736',
    manager: { name: 'Nasreddine Nabi', winPercentage: 55.0, preferredFormations: ['4-2-3-1'], careerTimeline: [], tacticalAnalysis: 'Attacking focus.', quote: 'We play for the fans.' },
    squad: [{ id: 'kc1', name: 'Itumeleng Khune', position: 'GK', age: 36, nationality: 'South Africa', marketValue: '€0.2M', form: 6.0, status: 'fit' }],
    tactics: { pressing: 70, buildUp: 'positional', defensiveLine: 'medium', transitionSpeed: 80 },
  },
  'as-vita': {
    id: 'as-vita',
    name: 'AS Vita Club',
    country: 'DR Congo',
    rank: 15,
    tier: 'B',
    titles: 1,
    leaguePosition: 2,
    lastFive: ['W', 'D', 'W', 'L', 'W'],
    nextFixture: 'vs TP Mazembe',
    formation: '4-3-3',
    stadium: 'Stade des Martyrs',
    capacity: '80,000',
    manager: { name: 'Abdeslam Ouaddou', winPercentage: 48.0, preferredFormations: ['4-3-3'], careerTimeline: [], tacticalAnalysis: 'Physical dominance.', quote: 'Strength in unity.' },
    squad: [
      { id: 'asv1', name: 'Élie Mpanzu', position: 'RW', age: 23, nationality: 'DR Congo', marketValue: '€0.3M', form: 7.8, status: 'fit', scoutNote: 'Pacey winger, good crosser.' },
      { id: 'asv101', name: 'Sofiane Louchène', position: 'CM', age: 29, nationality: 'Algeria', marketValue: '€0.2M', form: 5.2, status: 'fit', scoutNote: 'Lacks mobility in midfield.', isWeakPoint: true },
    ],
    tactics: { pressing: 80, buildUp: 'direct', defensiveLine: 'medium', transitionSpeed: 85 },
  },
  'usm-alger': {
    id: 'usm-alger',
    name: 'USM Alger',
    country: 'Algeria',
    rank: 12,
    tier: 'B',
    titles: 0,
    leaguePosition: 3,
    lastFive: ['W', 'D', 'W', 'W', 'L'],
    nextFixture: 'vs CR Belouizdad',
    formation: '4-2-3-1',
    stadium: 'Stade Omar Hamadi',
    capacity: '12,000',
    manager: { name: 'Nabil Maâloul', winPercentage: 60.0, preferredFormations: ['4-2-3-1'], careerTimeline: [], tacticalAnalysis: 'Tactical flexibility.', quote: 'Adapt to win.' },
    squad: [{ id: 'usm1', name: 'Oussama Chita', position: 'CDM', age: 27, nationality: 'Algeria', marketValue: '€0.7M', form: 8.0, status: 'fit' }],
    tactics: { pressing: 75, buildUp: 'positional', defensiveLine: 'medium', transitionSpeed: 75 },
  },
  'generation-foot': {
    id: 'generation-foot',
    name: 'Génération Foot',
    country: 'Senegal',
    rank: 55,
    tier: 'C',
    titles: 0,
    leaguePosition: 4,
    lastFive: ['D', 'W', 'L', 'W', 'D'],
    nextFixture: 'vs Jaraaf',
    formation: '4-3-3',
    stadium: 'Stade Déni Biram Ndao',
    capacity: '1,000',
    manager: { name: 'Djiby Fall', winPercentage: 52.0, preferredFormations: ['4-3-3'], careerTimeline: [], tacticalAnalysis: 'Youth development focus.', quote: 'The future is now.' },
    squad: [
      { id: 'gf1', name: 'Amara Diouf', position: 'LW', age: 15, nationality: 'Senegal', marketValue: '€1.0M', form: 9.5, status: 'fit', scoutNote: 'Generational talent, incredible pace and finishing.' },
      { id: 'gf101', name: 'Serigne Fallou Diouf', position: 'CB', age: 17, nationality: 'Senegal', marketValue: '€0.2M', form: 6.5, status: 'fit', scoutNote: 'Promising but raw, prone to positional errors.', isWeakPoint: true },
    ],
    tactics: { pressing: 85, buildUp: 'positional', defensiveLine: 'high', transitionSpeed: 90 },
  },
  'jaraaf': {
    id: 'jaraaf',
    name: 'ASC Jaraaf',
    country: 'Senegal',
    rank: 45,
    tier: 'B',
    titles: 0,
    leaguePosition: 1,
    lastFive: ['W', 'W', 'W', 'D', 'W'],
    nextFixture: 'vs Génération Foot',
    formation: '4-4-2',
    stadium: 'Stade Léopold Sédar Senghor',
    capacity: '60,000',
    manager: { name: 'Malick Daf', winPercentage: 58.0, preferredFormations: ['4-4-2'], careerTimeline: [], tacticalAnalysis: 'Balanced structure.', quote: 'Consistency is key.' },
    squad: [
      { id: 'jar1', name: 'Mouhamed Welle', position: 'CM', age: 24, nationality: 'Senegal', marketValue: '€0.2M', form: 7.2, status: 'fit', scoutNote: 'Hardworking midfielder.' },
      { id: 'jar101', name: 'Abdoulaye Diakhaté', position: 'CB', age: 35, nationality: 'Senegal', marketValue: '€0.1M', form: 5.8, status: 'fit', scoutNote: 'Experienced but slow on the turn.', isWeakPoint: true },
    ],
    tactics: { pressing: 70, buildUp: 'direct', defensiveLine: 'medium', transitionSpeed: 80 },
  },
  'coton-sport': {
    id: 'coton-sport',
    name: 'Coton Sport',
    country: 'Cameroon',
    rank: 38,
    tier: 'B',
    titles: 0,
    leaguePosition: 1,
    lastFive: ['W', 'W', 'D', 'L', 'W'],
    nextFixture: 'vs Canon Yaoundé',
    formation: '4-3-3',
    stadium: 'Stade Omnisports de Garoua',
    capacity: '30,000',
    manager: { name: 'Daniel Breard', winPercentage: 54.0, preferredFormations: ['4-3-3'], careerTimeline: [], tacticalAnalysis: 'Direct attacking.', quote: 'Attack with purpose.' },
    squad: [
      { id: 'cs1', name: 'Patient Wassou', position: 'ST', age: 20, nationality: 'Cameroon', marketValue: '€0.4M', form: 7.8, status: 'fit', scoutNote: 'Talented young striker.' },
      { id: 'cs101', name: 'Gwet Eno', position: 'CDM', age: 21, nationality: 'Cameroon', marketValue: '€0.2M', form: 5.9, status: 'fit', scoutNote: 'Aggressive but prone to bookings.', isWeakPoint: true },
    ],
    tactics: { pressing: 75, buildUp: 'direct', defensiveLine: 'medium', transitionSpeed: 85 },
  },
  'canon-yaounde': {
    id: 'canon-yaounde',
    name: 'Canon Yaoundé',
    country: 'Cameroon',
    rank: 60,
    tier: 'C',
    titles: 3,
    leaguePosition: 3,
    lastFive: ['D', 'W', 'W', 'L', 'D'],
    nextFixture: 'vs Coton Sport',
    formation: '4-4-2',
    stadium: 'Stade Ahmadou Ahidjo',
    capacity: '40,000',
    manager: { name: 'Minko Birwe', winPercentage: 48.0, preferredFormations: ['4-4-2'], careerTimeline: [], tacticalAnalysis: 'Physical game.', quote: 'Legendary spirit.' },
    squad: [
      { id: 'cy1', name: 'Emmanuel Mahop', position: 'ST', age: 28, nationality: 'Cameroon', marketValue: '€0.2M', form: 7.0, status: 'fit', scoutNote: 'Reliable goalscorer.' },
      { id: 'cy101', name: 'James Djaoyang', position: 'GK', age: 25, nationality: 'Cameroon', marketValue: '€0.1M', form: 5.4, status: 'fit', scoutNote: 'Weak on long-range shots.', isWeakPoint: true },
    ],
    tactics: { pressing: 70, buildUp: 'direct', defensiveLine: 'low', transitionSpeed: 75 },
  },
  'gor-mahia': {
    id: 'gor-mahia',
    name: 'Gor Mahia',
    country: 'Kenya',
    rank: 50,
    tier: 'C',
    titles: 0,
    leaguePosition: 1,
    lastFive: ['W', 'W', 'W', 'D', 'W'],
    nextFixture: 'vs AFC Leopards',
    formation: '4-2-3-1',
    stadium: 'Nyayo National Stadium',
    capacity: '30,000',
    manager: { name: 'Leonardo Neiva', winPercentage: 62.0, preferredFormations: ['4-2-3-1'], careerTimeline: [], tacticalAnalysis: 'High intensity.', quote: 'Sirkal!' },
    squad: [{ id: 'gm1', name: 'Benson Omala', position: 'ST', age: 22, nationality: 'Kenya', marketValue: '€0.3M', form: 9.2, status: 'fit' }],
    tactics: { pressing: 80, buildUp: 'positional', defensiveLine: 'medium', transitionSpeed: 85 },
  },
  'afc-leopards': {
    id: 'afc-leopards',
    name: 'AFC Leopards',
    country: 'Kenya',
    rank: 70,
    tier: 'C',
    titles: 0,
    leaguePosition: 4,
    lastFive: ['D', 'W', 'L', 'W', 'D'],
    nextFixture: 'vs Gor Mahia',
    formation: '4-3-3',
    stadium: 'Nyayo National Stadium',
    capacity: '30,000',
    manager: { name: 'Tomas Trucha', winPercentage: 50.0, preferredFormations: ['4-3-3'], careerTimeline: [], tacticalAnalysis: 'Wing play.', quote: 'Ingwe!' },
    squad: [{ id: 'afcl1', name: 'Victor Omune', position: 'AM', age: 26, nationality: 'Kenya', marketValue: '€0.1M', form: 7.4, status: 'fit' }],
    tactics: { pressing: 75, buildUp: 'direct', defensiveLine: 'medium', transitionSpeed: 80 },
  },
};

